/** @format */

export default {
  // Common phrases
  Exit: 'Thoát',
  HomeTown:'Quê quán',
  ExitConfirm: 'Bạn có chắc muốn thoát ra?',
  Edit: 'Sửa',
  Yes: 'Có',
  No: 'Không',
  OK: 'OK',
  Cancel: 'Bỏ qua',
  Update: 'Sửa',
  Sure: 'Chắc chắn',
  Done: 'Xong',
  ThankYou: 'Cảm ơn',
  Back: 'Quay lại',
  Close: 'Đóng',
  ClearSearch: 'Bỏ tìm kiếm',
  Confirm: 'Xác nhận',
  noConnection: 'KHÔNG CÓ KẾT NỐI INTERNET',
  Loading: 'Đang xử lý...',
  CancelItem: 'Huỷ hàng',
  ReturnItem: 'Trả hàng',
  HasProblem: 'Sự cố',
  Save: 'Lưu',
  NumberOfOrder: 'Số đơn',
  CartName: 'Giỏ',
  NumberOfCart: 'Số giỏ',
  Rest:'Đăng kí nghỉ',
  Schedule:'Lịch kíp',
  Shift: 'Kíp trực',
  JobCode: 'Mã nhân viên',
  Job: 'Chức vụ',
  ConfirmSchedule:'Đăng kí lịch',
  Khoang1:'Khoảng đăng kí 1',
  Khoang2:'Khoảng đăng kí 2',


  // Sceen's Titles
  Home: 'Trang chủ',
  Product: 'Mặt hàng',
  Order: 'Đơn hàng',
  Orders: 'Đơn hàng',
  SingleOrder: 'Đơn',
  SyntheticOrders: 'Các đơn hàng',
  Map: 'Bản đồ',
  Customers: 'Khách hàng',
  Customer: 'Khách hàng',
  Notifications: 'Thông báo',
  Account: 'Tài khoản',
  Code: 'Mã',
  Status: 'Trạng thái',
  Phone: 'Điện thoaị',
  Weight: 'Khối lượng',
  ConfirmArrived: 'Đã đến nơi',
  TimeShipping: 'Ngày giao hàng',
  Position: 'Vị trí',
  MonthRest:'Tháng đăng kí',
  MaxDay: 'Số ngày nghỉ max',

  // search
  Search: 'Tìm kiếm',
  Result: 'Kết quả',
  SelectDate: 'Chọn ngày',
  AllDate: 'Tất cả ngày',
  AllState: 'Tất cả trạng thái',
  SelectState: 'Trạng thái',

  // product
  Category: 'Nhóm hàng',
  Supplier: 'Nhà cung cấp',

  // user profile screen
  Name: 'Tên',
  Gender: 'Giới tính',
  Phone: 'Số Điện Thoại',
  Address: 'Địa chỉ',

  // Order
  Total: 'Tổng số',
  OrderNumber: 'Mã đơn hàng',
  SubTotal: 'Tiền hàng',
  Discount: 'Khuyến mại',
  PaidFromWallet: 'Trả từ ví Ubo',
  OrderTotal: 'Số tiền',
  TotalAmount: 'Tổng tiền',
  OrderDate: 'Ngày đặt hàng',
  DeliveryDate: 'Ngày giao hàng',
  POSAddress: 'Tại',
  State: 'Trạng thái',
  OrderStatus: 'Trạng thái',
  OrderDetails: 'Chi tiết',
  ConfirmShipped: 'Đã giao hàng',
  ConfirmCompleted: 'Đã hoàn thành',
  ConfirmReturned: 'Trả hàng',
  PrintOrder: 'In đơn hàng',
  ShareToPrintApp: 'Dùng phần mềm in',
  PurchasedOrdersCount: 'Đơn đã đặt',
  OrdersCount: 'Số đơn hàng',
  ShippingRequest: 'Yêu cầu ship',
  Note: 'Ghi chú',

  // Order state
  Pending: 'Chờ xử lý',
  Received: 'Đặt hàng',
  Processing: 'Đóng gói',
  Shipping: 'Vận chuyển',
  Shipped: 'Tới POS',
  Completed: 'Hoàn thành',
  Cancelled: 'Đã hủy',
  Returned: 'Đã trả lại',

  // LineItem
  ProductCode: 'Mã hàng',
  Quantity: 'Số lượng',
  TotalQuantity: 'Tổng số lượng',
  Unit: 'Qui cách',
  Weight: 'Khối lượng',
  TotalWeight: 'Tổng khối lượng',
  ListedPrice: 'Giá niêm yết',
  SellingPrice: 'Giá bán',
  ItemAmount: 'Thành tiền',

  // POS
  POS: 'POS',
  DefaultPOS: 'POS mặc định',

  // User
  Login: 'Đăng nhập',
  Logout: 'Đăng xuất',
  Guest: 'Chưa đăng nhập',
  LoggedOut: 'Bạn đã đăng xuất',
  LoginFailed: 'Có lỗi khi đăng nhập...',

  AccountInformation: 'Thông tin tài khoản',
  ResetPassword: 'Đổi mật khẩu',
  OldPassword: 'Mật khẩu cũ',
  NewPassword: 'Mật khẩu mới',
  ConfirmPassword: 'Xác nhận mật khẩu',
  ChangePassword: 'Đổi mật khẩu',
  ChangePasswordSuccess: 'Đổi mật khẩu thành công',
  ChangeProfileSuccess: 'Đổi thông tin thành công',

  // Error
  ErrorWhenPrintingOrder: 'Có lỗi khi in đơn hàng',
  CannotEditNotShippedLineitem: 'Chỉ sửa được đơn hàng đang vận chuyển hoặc đã tới POS',
  ErrorMessageRequest: 'Có lỗi khi kết nối với máy chủ',
  GetDataError: 'Có lỗi khi kết nối với máy chủ',
  NoConnection: 'Điện thoại đang không kết nối internet',
};
